package org.hs5tb.groospin.base

import org.hs5tb.groospin.common.IOTools

/**
 * Created by Alberto on 19-Jun-17.
 */
class Mame {
    String folder

    Mame folder(String folder) {
        this.folder = folder
        this
    }

    Mame backupAndCleanDefaultCfg() {
        File defaultCfg = new File(folder + "/cfg/default.cfg")
        if (defaultCfg.exists()) {
            Node mameconfig = new XmlParser().parse(defaultCfg)
            if (mameconfig.system.input.port.size() > 0) {
                String newName = (defaultCfg.name - ".cfg") + "-${new Date().format("yyyyMMdd-HHmmss")}.cfg"
                IOTools.move(defaultCfg, new File(defaultCfg.parentFile, newName))
            }
        }
        this
    }


    static String KEY_NONE = "KEYCODE_NONE"
    static String CODE_DEFAULT = "CODE_DEFAULT"
    static String CODE_NONE = "CODE_NONE"
    static String CODE_OR = "CODE_OR"
    static String CODE_PREVIOUS = "CODE_PREVIOUS"

    static String J1_BUTTON1 = "JOYCODE_1_BUTTON1"
    static String J1_BUTTON2 = "JOYCODE_1_BUTTON2"
    static String J1_BUTTON3 = "JOYCODE_1_BUTTON3"
    static String J1_BUTTON4 = "JOYCODE_1_BUTTON4"
    static String J1_BUTTON5 = "JOYCODE_1_BUTTON5"
    static String J1_BUTTON6 = "JOYCODE_1_BUTTON6"
    static String J1_DOWN = "JOYCODE_1_DOWN"
    static String J1_LEFT = "JOYCODE_1_LEFT"
    static String J1_RIGHT = "JOYCODE_1_RIGHT"
    static String J1_SELECT = "JOYCODE_1_SELECT"
    static String J1_START = "JOYCODE_1_START"
    static String J1_UP = "JOYCODE_1_UP"

    static String J1_DPAD_UP = "JOYCODE_1_DPADUP"
    static String J1_DPAD_DOWN = "JOYCODE_1_DPADDOWN"
    static String J1_DPAD_LEFT = "JOYCODE_1_DPADLEFT"
    static String J1_DPAD_RIGHT = "JOYCODE_1_DPADRIGHT"

    static String J1_LANA_UP = "JOYCODE_1_YAXIS_UP_SWITCH"
    static String J1_LANA_DOWN = "JOYCODE_1_YAXIS_DOWN_SWITCH"
    static String J1_LANA_LEFT = "JOYCODE_1_XAXIS_LEFT_SWITCH"
    static String J1_LANA_RIGHT = "JOYCODE_1_XAXIS_RIGHT_SWITCH"

    static String J1_RANA_UP = "JOYCODE_1_RYAXIS_NEG_SWITCH"
    static String J1_RANA_DOWN = "JOYCODE_1_RYAXIS_POS_SWITCH"
    static String J1_RANA_LEFT = "JOYCODE_1_RXAXIS_NEG_SWITCH"
    static String J1_RANA_RIGHT = "JOYCODE_1_RXAXIS_POS_SWITCH"

    static String J1_LT_ANA = "JOYCODE_1_ZAXIS_NEG_SWITCH" // bug?? no deberia ser ...1_RZ... le falta la R!!
    static String J1_RT_ANA = "JOYCODE_1_RZAXIS_POS_SWITCH"

    static String J2_BUTTON1 = "JOYCODE_2_BUTTON1"
    static String J2_BUTTON2 = "JOYCODE_2_BUTTON2"
    static String J2_BUTTON3 = "JOYCODE_2_BUTTON3"
    static String J2_BUTTON4 = "JOYCODE_2_BUTTON4"
    static String J2_BUTTON5 = "JOYCODE_2_BUTTON5"
    static String J2_BUTTON6 = "JOYCODE_2_BUTTON6"
    static String J2_DOWN = "JOYCODE_2_DOWN"
    static String J2_LEFT = "JOYCODE_2_LEFT"
    static String J2_RIGHT = "JOYCODE_2_RIGHT"
    static String J2_SELECT = "JOYCODE_2_SELECT"
    static String J2_START = "JOYCODE_2_START"
    static String J2_UP = "JOYCODE_2_UP"

    static String KEY_F1 = "KEYCODE_F1"
    static String KEY_F2 = "KEYCODE_F2"
    static String KEY_F3 = "KEYCODE_F3"
    static String KEY_F4 = "KEYCODE_F4"
    static String KEY_F5 = "KEYCODE_F5"
    static String KEY_F6 = "KEYCODE_F6"
    static String KEY_F7 = "KEYCODE_F7"
    static String KEY_F8 = "KEYCODE_F8"
    static String KEY_F9 = "KEYCODE_F9"
    static String KEY_F10 = "KEYCODE_F10"
    static String KEY_F11 = "KEYCODE_F11"
    static String KEY_F12 = "KEYCODE_F12"

    static String J3_BUTTON1 = "JOYCODE_3_BUTTON1"
    static String J3_BUTTON2 = "JOYCODE_3_BUTTON2"
    static String J3_BUTTON3 = "JOYCODE_3_BUTTON3"
    static String J3_BUTTON4 = "JOYCODE_3_BUTTON4"
    static String J3_BUTTON5 = "JOYCODE_3_BUTTON5"
    static String J3_BUTTON6 = "JOYCODE_3_BUTTON6"
    static String J3_DOWN = "JOYCODE_3_DOWN"
    static String J3_LEFT = "JOYCODE_3_LEFT"
    static String J3_RIGHT = "JOYCODE_3_RIGHT"
    static String J3_SELECT = "JOYCODE_3_SELECT"
    static String J3_START = "JOYCODE_3_START"
    static String J3_UP = "JOYCODE_3_UP"

    static String J4_BUTTON = "JOYCODE_4_BUTTON"
    static String J4_BUTTON1 = "JOYCODE_4_BUTTON1"
    static String J4_BUTTON2 = "JOYCODE_4_BUTTON2"
    static String J4_BUTTON3 = "JOYCODE_4_BUTTON3"
    static String J4_BUTTON4 = "JOYCODE_4_BUTTON4"
    static String J4_BUTTON5 = "JOYCODE_4_BUTTON5"
    static String J4_DOWN = "JOYCODE_4_DOWN"
    static String J4_LEFT = "JOYCODE_4_LEFT"
    static String J4_RIGHT = "JOYCODE_4_RIGHT"
    static String J4_SELECT = "JOYCODE_4_SELECT"
    static String J4_START = "JOYCODE_4_START"
    static String J4_UP = "JOYCODE_4_UP"

    static String KEY_UP = "KEYCODE_UP"
    static String KEY_DOWN = "KEYCODE_DOWN"
    static String KEY_LEFT = "KEYCODE_LEFT"
    static String KEY_RIGHT = "KEYCODE_RIGHT"

    static String KEY_A = "KEYCODE_A"
    static String KEY_B = "KEYCODE_B"
    static String KEY_C = "KEYCODE_C"
    static String KEY_D = "KEYCODE_D"
    static String KEY_E = "KEYCODE_E"
    static String KEY_F = "KEYCODE_F"
    static String KEY_G = "KEYCODE_G"
    static String KEY_H = "KEYCODE_H"
    static String KEY_I = "KEYCODE_I"
    static String KEY_J = "KEYCODE_J"
    static String KEY_K = "KEYCODE_K"
    static String KEY_L = "KEYCODE_L"
    static String KEY_M = "KEYCODE_M"
    static String KEY_N = "KEYCODE_N"
    static String KEY_O = "KEYCODE_O"
    static String KEY_P = "KEYCODE_P"
    static String KEY_Q = "KEYCODE_Q"
    static String KEY_R = "KEYCODE_R"
    static String KEY_S = "KEYCODE_S"
    static String KEY_T = "KEYCODE_T"
    static String KEY_U = "KEYCODE_U"
    static String KEY_V = "KEYCODE_V"
    static String KEY_W = "KEYCODE_W"
    static String KEY_X = "KEYCODE_X"
    static String KEY_Y = "KEYCODE_Y"
    static String KEY_Z = "KEYCODE_Z"

    static String KEY_0_PAD = "KEYCODE_0_PAD"
    static String KEY_1_PAD = "KEYCODE_1_PAD"
    static String KEY_2_PAD = "KEYCODE_2_PAD"
    static String KEY_3_PAD = "KEYCODE_3_PAD"
    static String KEY_4_PAD = "KEYCODE_4_PAD"
    static String KEY_5_PAD = "KEYCODE_5_PAD"
    static String KEY_6_PAD = "KEYCODE_6_PAD"
    static String KEY_7_PAD = "KEYCODE_7_PAD"
    static String KEY_8_PAD = "KEYCODE_8_PAD"
    static String KEY_9_PAD = "KEYCODE_9_PAD"
    static String KEY_DEL_PAD = "KEYCODE_DEL_PAD"
    static String KEY_ENTER_PAD = "KEYCODE_ENTER_PAD"
    static String KEY_MINUS_PAD = "KEYCODE_MINUS_PAD"
    static String KEY_PLUS_PAD = "KEYCODE_PLUS_PAD"
    static String KEY_SLASH_PAD = "KEYCODE_SLASH_PAD"

    static String KEY_NUMLOCK = "KEYCODE_NUMLOCK"

    static String KEY_0 = "KEYCODE_0"
    static String KEY_1 = "KEYCODE_1"
    static String KEY_2 = "KEYCODE_2"
    static String KEY_3 = "KEYCODE_3"
    static String KEY_4 = "KEYCODE_4"
    static String KEY_5 = "KEYCODE_5"
    static String KEY_6 = "KEYCODE_6"
    static String KEY_7 = "KEYCODE_7"
    static String KEY_8 = "KEYCODE_8"
    static String KEY_9 = "KEYCODE_9"

    static String KEY_DEL = "KEYCODE_DEL"
    static String KEY_END = "KEYCODE_END"
    static String KEY_HOME = "KEYCODE_HOME"
    static String KEY_INSERT = "KEYCODE_INSERT"
    static String KEY_PGDN = "KEYCODE_PGDN"
    static String KEY_PGUP = "KEYCODE_PGUP"

    static String KEY_PAUSE = "KEYCODE_PAUSE"
    static String KEY_PRTSCR = "KEYCODE_PRTSCR"
    static String KEY_SCRLOCK = "KEYCODE_SCRLOCK"

    static String KEY_LWIN = "KEYCODE_LWIN"
    static String KEY_RWIN = "KEYCODE_RWIN"

    static String KEY_CAPSLOCK = "KEYCODE_CAPSLOCK"
    static String KEY_ENTER = "KEYCODE_ENTER"
    static String KEY_LALT = "KEYCODE_LALT"
    static String KEY_LCONTROL = "KEYCODE_LCONTROL"
    static String KEY_LSHIFT = "KEYCODE_LSHIFT"
    static String KEY_RALT = "KEYCODE_RALT"
    static String KEY_RCONTROL = "KEYCODE_RCONTROL"
    static String KEY_RSHIFT = "KEYCODE_RSHIFT"
    static String KEY_SPACE = "KEYCODE_SPACE"
    static String KEY_TAB = "KEYCODE_TAB"
    static String KEY_ESC = "KEYCODE_ESC"
    static String KEY_BACKSPACE = "KEYCODE_BACKSPACE"
    static String KEY_MENU = "KEYCODE_MENU"

    static String KEY_ASTERISK = "KEYCODE_ASTERISK"
    static String KEY_BACKSLASH = "KEYCODE_BACKSLASH"
    static String KEY_BACKSLASH2 = "KEYCODE_BACKSLASH2"
    static String KEY_CLOSEBRACE = "KEYCODE_CLOSEBRACE"
    static String KEY_COLON = "KEYCODE_COLON"
    static String KEY_COMMA = "KEYCODE_COMMA"
    static String KEY_EQUALS = "KEYCODE_EQUALS"
    static String KEY_MINUS = "KEYCODE_MINUS"
    static String KEY_OPENBRACE = "KEYCODE_OPENBRACE"
    static String KEY_QUOTE = "KEYCODE_QUOTE"
    static String KEY_SLASH = "KEYCODE_SLASH"
    static String KEY_STOP = "KEYCODE_STOP"
    static String KEY_TILDE = "KEYCODE_TILDE"

    static String MOUSECODE_1_BUTTON1 = "MOUSECODE_1_BUTTON1"
    static String MOUSECODE_1_BUTTON2 = "MOUSECODE_1_BUTTON2"
    static String MOUSECODE_1_BUTTON3 = "MOUSECODE_1_BUTTON3"

    static class Config {
        static String COIN1 = "COIN1"
        static String COIN2 = "COIN2"
        static String COIN3 = "COIN3"
        static String COIN4 = "COIN4"
        static String START1 = "START1"
        static String START2 = "START2"
        static String START3 = "START3"
        static String START4 = "START4"
        static String SERVICE1 = "SERVICE1"
        static String SERVICE2 = "SERVICE2"
        static String SERVICE3 = "SERVICE3"
        static String SERVICE4 = "SERVICE4"
        static String TILT = "TILT"
        static String UI_UP = "UI_UP"
        static String UI_RIGHT = "UI_RIGHT"
        static String UI_LEFT = "UI_LEFT"
        static String UI_DOWN = "UI_DOWN"
        static String UI_SELECT = "UI_SELECT"
        static String UI_CANCEL = "UI_CANCEL"
        static String UI_PAUSE = "UI_PAUSE"
        static String UI_LOAD_STATE = "UI_LOAD_STATE"
        static String UI_SAVE_STATE = "UI_SAVE_STATE"
        static String UI_ADD_CHEAT = "UI_ADD_CHEAT"
        static String UI_DELETE_CHEAT = "UI_DELETE_CHEAT"
        static String UI_SAVE_CHEAT = "UI_SAVE_CHEAT"
        static String UI_EDIT_CHEAT = "UI_EDIT_CHEAT"
        static String UI_SHOW_FPS = "UI_SHOW_FPS"
        static String UI_THROTTLE = "UI_THROTTLE"
        static String UI_FRAMESKIP_DEC = "UI_FRAMESKIP_DEC"
        static String UI_FRAMESKIP_INC = "UI_FRAMESKIP_INC"
        static String P1_BUTTON1 = "P1_BUTTON1"
        static String P1_BUTTON2 = "P1_BUTTON2"
        static String P1_BUTTON3 = "P1_BUTTON3"
        static String P1_BUTTON4 = "P1_BUTTON4"
        static String P1_BUTTON5 = "P1_BUTTON5"
        static String P1_BUTTON6 = "P1_BUTTON6"
        static String P1_BUTTON7 = "P1_BUTTON7"
        static String P1_BUTTON8 = "P1_BUTTON8"
        static String P1_BUTTON9 = "P1_BUTTON9"
        static String P1_BUTTON10 = "P1_BUTTON10"
        static String P1_JOYSTICK_DOWN = "P1_JOYSTICK_DOWN"
        static String P1_JOYSTICK_LEFT = "P1_JOYSTICK_LEFT"
        static String P1_JOYSTICK_RIGHT = "P1_JOYSTICK_RIGHT"
        static String P1_JOYSTICK_UP = "P1_JOYSTICK_UP"
        static String P1_JOYSTICKLEFT_DOWN = "P1_JOYSTICKLEFT_DOWN"
        static String P1_JOYSTICKLEFT_LEFT = "P1_JOYSTICKLEFT_LEFT"
        static String P1_JOYSTICKLEFT_RIGHT = "P1_JOYSTICKLEFT_RIGHT"
        static String P1_JOYSTICKLEFT_UP = "P1_JOYSTICKLEFT_UP"
        static String P1_JOYSTICKRIGHT_DOWN = "P1_JOYSTICKRIGHT_DOWN"
        static String P1_JOYSTICKRIGHT_LEFT = "P1_JOYSTICKRIGHT_LEFT"
        static String P1_JOYSTICKRIGHT_RIGHT = "P1_JOYSTICKRIGHT_RIGHT"
        static String P1_JOYSTICKRIGHT_UP = "P1_JOYSTICKRIGHT_UP"

    }
    
}
